### ISSUE TITLE
Boolean operators in search/filter query syntax

### ISSUE THREAD

**Issue by MikeThacker1** [openreferral/api-specification#102]
We need a means of expressing how different filter parameters are combined. I believe GraphQL has been raised before. With a couple of exception (page={pageNumber} is the main one) we have said that all filter parameters are combined with a Boolean AND except where they are comma-delimited. values eg /services?taxonomy_id=123,234

**Comment by kinlane** [comment]
A recommendation and guidance for a GraphQL endpoint would satisfy, but would definitely need more discussion. Would be nice to have boolean operator pattern for the core design. Will include as part of discussion for v2.0.

**Comment by kinlane** [comment]
I am adopting an approach similar to GitHubs:

- [Github](https://docs.github.com/en/free-pro-team@latest/rest/reference/search)
- [Working thoughts](https://github.com/openreferral/api-specification/blob/master/query.md)
