### ISSUE TITLE
Returning identifiers for linked objects

### ISSUE THREAD

**Issue by MikeThacker1** [openreferral/api-specification#103]
We need clarity on when/if identiers used to link objects (eg a service's locations) are returned by web methods.

HSDS simple calls like /services/ return just identifiers for related objects like a service’s organization. We took the approach of returning the full object structure

HSDS complete calls like /services/complete/ return both the identifiers and (separately) full object structures. Hence there is redundancy in the response. Our verbose calls return full object structures, but do not separately return the objects’ identifiers. That is, We remove identifiers used to link objects within a response.

**Comment by kinlane** [comment]
It would make sense to use the move to v2.0 to remove these from default full response. Then add parameter for those who wish to have returned -- providing granular level API requests.
