### ISSUE TITLE
Naming of single and plural objects in query responses

### ISSUE THREAD

**Issue by MikeThacker1** [openreferral/api-specification#104]
The HSDS query response format for /services/complete/{service_id}/ has a mixture of singular and plural naming for parameters that can have multiple values, eg "contacts" (plural) and "service_area" (singular).

We use a plural form, even where grammatically incorrect, eg in the response to /services/id we use "contacts", "service_areas" and "service_taxonomys".

Although it would be a breaking change, there is merit in taking a mechanistic approach to always pluralise such items in a consistent way.

**Comment by kinlane** [comment]
Definitely the time to audit and review as part of migration to v2.0. Thanks!

**Comment by kinlane** [comment]
This method has been removed from v2.0, and we'll be auditing plurality use across all existing methods as part of release.
