### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#11]
How will we be filtering API responses? Right now we depend on the /search/ path to do search, with the following fields:

category:	
email:	
keyword:	
language:	
lat_lng:	
location:	
org_name:	
radius:	
service_area:	
status:	

How will this be applied across paths?

**Comment by NeilMcKechnie** [comment]
I'll comment on the search parameters in a separate thread, but I think what you may be asking is: How are these search parameters applied when looking for specific object types, like Contacts or Addresses? If that is what you are asking, I would say that we'd have to look at the use cases to help answer that. I predominantly look through the lens of Organization, Location and Service and then everything else attaches directly or indirectly to that. So, search should be capable of looking in any/all object types but then the Response should include those parent objects linked to the secondary objects, for context.

**Comment by kinlane** [comment]
Going to run with #49 --closing this one out.
