### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#12]
How will we be sorting information. There is no sorting capability in the current design.

**Comment by NeilMcKechnie** [comment]
We need at least Alphabetical and Proximity (if a search reference location is included). A third option is Relevance which opens a big can of worms about how relevance is calculated. We could just keep that can closed for now though, leave it as a sorting option, and let each implementer decide how to calculate and sort via Relevance.

**Comment by timgdavies** [comment]
A last-updated (descending) sort will be important for synchronisation use-cases.

**Comment by kinlane** [comment]
Suggesting we run with 

sortby ([fieldname],last-updated)
order  (asc,desc)

leaving proximity for futue release, and possibility limited to HSDA search.

combinging simplicity, best practices, and above feedback.

**Comment by timgdavies** [comment]
Would this only allow sorting by fields in the top resource? Or would we allow a syntax of field paths to access sub-resources in the `/full` / `/complete` representations (or even when `/complete` is not requested)? 

For example, I might want to search for organizations, but sort the results based on thee funding source of their services. 

Could this be expressed as:

``
?sortby=organizations/services/funding/source&order=asc
``

**Comment by kinlane** [comment]
with this release I kept just top level. Plan is to go next level with next release. Trying to minimize the change.  Thanks for brining up!

**Comment by rasmus-storjohann-PG** [comment]
A possible alternative to the `order` parameter is an optional `-` prefix on each of the fields passed to `sortby`, that way it's possible to sort ascending by one field and descending by another.

**Comment by kinlane** [comment]
@rasmus-storjohann-PG I like that concept. Will be evaluating.

**Comment by kinlane** [comment]
Keeping single parameter order by as the default, and will be adding robust search capabilities to /search.

``
      - in: query
        name: sort_by
        description: Which field to sort by.
        schema:
          type: string
      - in: query
        name: order
        description: Which order to sort by (asc,desc).
        schema:
          type: string
``
