### ISSUE TITLE
Definitions on openreferral.github.io get a 404

### ISSUE THREAD

**Issue by greggish** [openreferral/api-specification#15]
Aside from Documentation, the links at https://openreferral.github.io are turning up 404...

**Comment by spilio** [comment]
@greggish The base URL is https://openreferral.github.io/api-specification/.

**Comment by greggish** [comment]
Now openreferral.github.io itself is 404

**Comment by kinlane** [comment]
What did it go to before? It is the root of the account, and I never had something posted here.

**Comment by timgdavies** [comment]
@greggish If you let me know where you think this should direct as part of your website update suggestions, I'll set up a simple redirect for this.

**Comment by kinlane** [comment]
So this is a Github feature. You create a repo with your orgname.github.io -- so, openreferral.github.io -- which I just did. 

The index page can have any content - https://github.com/openreferral/openreferral.github.io/blob/master/index.html

What would you like @greggish  ?

**Comment by greggish** [comment]
Cool. I think this could make for an ecosystem landing page, pointing to spec(s) and tools. For now, though, can we just redirect to docs.openreferral.org?

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case we provide comprehensive documentation in the Open Referral docs site https://docs.openreferral.org
