### ISSUE TITLE
Scheduling and Calendaring

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#23]
Had a comment come in on a blog post that I want to consider for future road map when it comes to expanding on the regular and holiday scheduling. 

**Source:** http://apievangelist.com/2017/05/23/avoid-moving-too-fast-for-my-api-audience/#comment-3321395153

**Abstract:** I am very familiar with 211 from the service provider standpoint. The NAACP in Eugene provides a weekly tutoring session at the local community college for students of color. Every year I have to update our listing on 211. Our schedule ends up changing as the school year progresses and we keep all the events on our wordpress site. I have dreamed of a day when a plug in would arrive so the 211 site would "listen" for changes on the events app on word press. This would make it so I could easily update our 211 listing with the most current info. I am probably not alone and a lot of small daycare providers, tutors, camps and counselors are using wordpress and other out of the box (OOB) websites to manage their events. Can we get some API action from the calendar devs on the OOB websites? (please note I am not a developer, just a user)

**Comment by greggish** [comment]
This speaks directly to our fourth 'type of use': Organization updating their own service information. 

cc @johnhbenetech

**Comment by timgdavies** [comment]
I've opened an issue in the HSDS specification repository related to this: https://github.com/openreferral/specification/issues/168

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case https://github.com/openreferral/specification/issues/168 is the appropriate place to discuss this issue
