### ISSUE TITLE
HSDS/A Validator

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#32]
I have a working JSON schema API that we can pass any JSON file to it and it will validate against a JSON schema.

I need to finish JSON schema representation for:

* HSDS - A representation to define the rules for the schema
* HSDA - A representation to define the surface area of the API.

I am still polishing my JSON schema chops, but also I'm thinking deeply about a mininum viable definition, as well as potentially more verbose definitions.

I'm thinking that we should be allowing for different levels of compliance.

This thinking overlaps with the schema filtering conversaiton for the API -- whether someone wants to see simple or complex responses, or even POST/PUT to the API - [Issue 21](https://github.com/openreferral/api-specification/issues/21).

**Comment by NeilMcKechnie** [comment]
Don't hold out on us @kinlane , let us take a peek at these tools - I think these will be vital to help with interoperability.

**Comment by kinlane** [comment]
Closing as duplicate of #43
