### ISSUE TITLE
Typo in table name INTERPRETATION_SERVICES

### ISSUE THREAD

**Issue by MaxWhitney** [openreferral/api-specification#33]
The table name INTEPRETATION_SERVICES is probably meant to be INTERPRETATION_SERVICES in the .yaml file.

Now that I'm digging though, I'm not sure which git repo file is the correct yaml file. This issue relates to the yaml in the documentation at https://openreferral.github.io/api-specification/definition/yaml/

**Comment by kinlane** [comment]
The specification will always be located within _data/api-commons/  with full URL https://github.com/openreferral/api-specification/blob/master/_data/api-commons/openapi.yaml. 

And your correction still applies -- thanks. Will fix shortly.

**Comment by kinlane** [comment]
This has been fixed, and will be pushed out with next release.
