### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#37]
I'd like to introduce guidance for messaging. Suggesting it is a standalone layer to the system that other areas use. To suppor the approval, and other aspects of the system we will need messaging.

I'm thinking this will include email, SMS, and potentially Github issues and Slack integration when it makes sense. Possibly even a templating system.

**Comment by NeilMcKechnie** [comment]
@kinlane can you expand and clarify please? Are you referring to these as just field values in HSDS? Was it more related to your webhooks topic in this forum?

**Comment by kinlane** [comment]
I'm talking about providing guidance for any sort of of email, MMS, or other protocol coming out of any HSDA implementation. I have no specific examples of this in the current spec, but wanted to have a place to discuss because yes the webhooks would have "notification" as option. 

My recommendation would be to keep email as separate service, not impacting HSDA or any other projects, but could to leveraged by any system. Helping keep messaging consistent.

I don't have this part of any version or project. currently.
