### ISSUE TITLE
Project Scope / Filtering

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#40]
Introducing a fourth dimension of the scope / filtering conversation -- project level. How do parts of the schema and API definition get grouped, and evolved separately from other projects.

How is this separation described in API definition(s) - OpenAPI + APIs.json, which can then be reflected in documentation, SDKs, and other tooling.

This also needs to be thought about as it impacts the definition for a "HSDA compliant API or schema" - what % compliant is an API. Few will ever be 100% compliant, but providers can pick and choose which project areas they support or don't support.

**Comment by NeilMcKechnie** [comment]
@kinlane a simple way to start slicing this would be by CRUD activity. I suspect most of us will start with Reads first. Updates would make sense to add next if going sequentially. Then Create and Delete last of all. So one could claim (and be validated against that claim) to support one or more of those operations.

**Comment by kinlane** [comment]
I'm breaking things down into:

- HSDA
- HSDA Search
- HSDA Bulk
- HSDA Meta
- HSDA Taxonomy
- HSDA Management
- HSDA Orchestration
- HSDA Utility
- HSDA Aggregation

Which I will just reflect in practice through tagging, no need for issue.
