### ISSUE TITLE
HTTP Status Codes

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#48]
Provide guidance on HTTP Status codes to be returned. Add all relevant HTTP Status Codes to individual endpoints using the OpenAPI.

**Comment by tuckerbuchy** [comment]
I think a key one here is `304`, which is used for reducing the amount of data transferred (https://httpstatuses.com/304). 

We should just duplicate the 200 response.

**Comment by NeilMcKechnie** [comment]
This was already discussed in an earlier topic. There are interesting error codes beyond just 200 and 404 we should implement. @kinlane I believe you articulated them in that other topic.

**Comment by kinlane** [comment]
So two elements here: 

1) HTTP Status codes - Which status codes are returned as part of each response. 
2) Error Codes (#47) - When a 500, or other error is encountered, what is returned. What is the structure of the message returned, and what does it contain. It won't be any of the HSDS schema.

When v1.2 draft is ready I will be spending time evaluating what next wave beyond just 200, and 400 should be returned. Along with Error codes for 500, along with any corresponding error status codes -- including 304 to my working list as  @tuckerbuchy suggested.

**Comment by kinlane** [comment]
We will be providing the following guidance for v2 on status codes -- the OpenAPI will reflect hat. 

## GET

- 200
- 403
- 500

## POST

- 200
- 403
- 500

## PUT

- 204
- 403
- 500

## DELETE

- 204
- 403
- 500
