### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#5]
what are the headers, and stragegy for this.

**Comment by kinlane** [comment]
Currently just putting API keys x-appid and x-appkey as headers. No other headers currently. Possibly considering using the HTTP Prefer Header for schema filtering.

**Comment by NeilMcKechnie** [comment]
Kin, we use headers in our API to express things like language (of records) requested, content-type, bearer token, etc. Is that what you have in mind?

**Comment by kinlane** [comment]
Yes, I will just be using this to provide a link to all headers in use. Currently it is just default stuff, including content-type. No real action needed here.

**Comment by kinlane** [comment]
Well, now I'm considering using as part of paging, count for responses, to keep message clean. still pondering and playing.

**Comment by kinlane** [comment]
This is no longer relevant with a move to v2, and the OpenAPI should define the header strategy.
