### ISSUE TITLE
Create Sample Dataset for ALL models

### ISSUE THREAD

**Issue by tuckerbuchy** [openreferral/api-specification#60]
Currently, there is a sample data set here: 
https://github.com/openreferral/sample-data
But this only contains a subset of the models in the specification. 
We should add the rest of these models so that this data is complete and can be used in prototyping and automated testing.

**Comment by timgdavies** [comment]
This is a good idea - and would be welcome - perhaps as a separate 'complete' directory. 

Do you know of any data-faker scripts for datapackages?  Or would this need manual creation?

**Comment by timgdavies** [comment]
Ah - I just saw your pull request. That's great. 

Contacts in the simple example makes good sense.

**Comment by NeilMcKechnie** [comment]
Perhaps we ask entities that have datasets to voluntarily contribute examples?

**Comment by greggish** [comment]
@NeilMcKechnie could you all be the first to step forth?

**Comment by NeilMcKechnie** [comment]
Happy to do so, I just want to polish up our HSDS 1.1 implementation and ideally run it through @kinlane 's forthcoming validators too!

**Comment by tuckerbuchy** [comment]
Sorry should have linked this here: 
https://github.com/openreferral/sample-data/pull/1

Just another note, I used mockaroo for the test data gen, it would be nice to have one of these per table.

Here is the Contact one that I created (also can find this link in the PR)
https://www.mockaroo.com/a46df0c0

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case the HSDS specification has a [folder of examples](https://github.com/openreferral/specification/tree/3.0/examples)
