### ISSUE TITLE
Full-record Insert, Update and Deletes

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/api-specification#61]
Related to Issue 26: https://github.com/openreferral/api-specification/issues/26 

How does one do a full-record Insert, Update and/or Delete (say, an Organization and all related/child records) without having to call the endpoint for each record type? For even moderately sized Organization records, you could end up with hundreds or thousands of write requests to the API for a single Organization, when you add up all the Addresses, Contacts, Phones, and all of the subrecord types.

Should we consider a way to push full groups of records in a single request, at least for, say, the "core" record types of Organziation, Service and Location? This is sort of the "write" side of the coin versus the topics about which fields and subrecord types to return in GETs (simple, complete, custom).

**Comment by kinlane** [comment]
POST and PUT on /everything for all central resources #45 

Basic DELETE on any core resource should delete its subresources

**Comment by kinlane** [comment]
Gonna close this as its a dupe.
