### ISSUE TITLE
Is SERVICE_AT_LOCATION appropriately missing in HSDA v 1.2?

### ISSUE THREAD

**Issue by MaxWhitney** [openreferral/api-specification#68]
The HSDA v 1.2 no longer has a description for a SERVICE_AT_LOCATION entity, though multiple entities reference a SERVICE_AT_LOCATION_ID field. I just want to make sure the absence is appropriate in the API and is not an oversight.

**Comment by rasmus-storjohann-PG** [comment]
As we were implementing sort of services by proximity, due to the many2many relationship between locations and services, it seemed to come very naturally that proximity sort be available at the /services_at_location/ end-point, so this end point is present (and important) in our implementation.

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case, HSDS 3.0 has a service_at_location object, and a corresponding API endpoint
