### ISSUE TITLE
Should NAME be a required field of LOCATION in HSDA 1.2

### ISSUE THREAD

**Issue by MaxWhitney** [openreferral/api-specification#69]
Version 1.1 of HSDS did not have NAME as a required field in LOCATION.

Version 1.2 of HSDA introduces NAME as a required field in LOCATION at line 637 of https://github.com/openreferral/api-specification/blob/master/_data/api-commons/openapi-hsda.yaml#L6377

Is this as intended, since it feels like a reversion to an earlier version of the HSDS spec?

**Comment by kinlane** [comment]
Closing due to v2.0 release rendering out of date.
