### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by greggish** [openreferral/api-specification#71]
I could be missing something, but I don't think we've assigned a license to the API spec in this repository. Can we address this?

In [the project charter](https://docs.google.com/document/d/1xPYDDDkjxSEmj5UubzzETqDbw-5-dCS1XEPCOXLcJss/edit#heading=h.8aad1zimbdqt), we declared it would be CC 4.0 BY-SA.

**Comment by timgdavies** [comment]
I've added a license, and updated the license in each YAML file for 1.2
