### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by greggish** [openreferral/api-specification#72]
We have [this thorough blog post of changes from v1.1 to v1.2](http://apievangelist.com/2017/09/11/version-1-2-of-human-services-data-api/). Would be great to have a brief running list of bulleted changes version-to-version a la [HSDS changelog](https://github.com/openreferral/specification/blob/master/docs/hsds-changelog.md).

**Comment by kinlane** [comment]
Agreed. There should be a roadmap list as part of documentation, with links to the issues showing the conversations

**Comment by mrshll1001** [comment]
We will be archiving this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case, changes to the API are versioned as part of HSDS and will be integrated into its changelog
