### ISSUE TITLE
Wrong definitions for /locations/{location_id}/physical-address/ requests

### ISSUE THREAD

**Issue by vtimonov** [openreferral/api-specification#75]
The requests below should be specified for the physical addresses of a specific location, but in  [openapi-hsda.yaml](https://github.com/openreferral/api-specification/blob/master/_data/api-commons/openapi-hsda.yaml) they are defined as **postal-address**:

[/locations/{location_id}/physical-address/ ](https://github.com/openreferral/api-specification/blob/bfb030133974d65a0a44bc73ca722936ac591ee7/_data/api-commons/openapi-hsda.yaml#L1423)
[/locations/{location_id}/physical-address/{postal_address_id}/](https://github.com/openreferral/api-specification/blob/bfb030133974d65a0a44bc73ca722936ac591ee7/_data/api-commons/openapi-hsda.yaml#L1487)

```
/locations/{location_id}/physical-address/:
    get:
      summary: Get physical addresses for location
      description: Returns a list of physical addresses for a specific location
      operationId: listLocationPhysicalAddresses
      parameters:
        - in: path
          required: true
          type: string
          name: location_id
          description: 'The unique location id.'
      responses:
        '200':
          description: Postal Address Response
          schema:
            type: array
            items:
              $ref: "#/definitions/postal_address"
```

**Comment by kinlane** [comment]
This has been cleaned up in the latest copy of the OpenAPI definition.
