### ISSUE TITLE
Search services by taxonomy.

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#76]
This was submitted via a document by ISS:

Can you retrieve a list of services in more than child taxon, but excluding other child taxons? Ie under “childcare” you may have “general”, “special needs”, “before school”, “after school”. If a user wanted general + before, but did not need to see special or after school, would that require 2 taxon requests or just one?

**Comment by kinlane** [comment]
Also: Consider adding parameters for taxonomy, accreditation, jurisdictional support (eg veteran cards, low income support), geographic location, max distance from user, transport options etc.

**Comment by NeilMcKechnie** [comment]
I recommend a more simple boolean search parameter to indicate "search in child taxonomy terms" with possible values of True or False. Then you simply search at the most granular term for which you want results and for which the child terms are also relevant. Further, one should be able to supply more than one taxonomy term in which to search and then be able to indicate how they should be "booleaned" together: AND or OR. 

These two different parameters in practice work very well in combination with each other in a multitude of different use cases I contributed to in the "real world".

**Comment by kinlane** [comment]
Will be applying the boolean search as part of the search service by taxonomy interface. Thanks @NeilMcKechnie

**Comment by mrshll1001** [comment]
We will be arching this repository soon. We're closing this issue because we believe it has been conclusively addressed as part of work on the main HSDS standard.

In this case, the HSDS 3.0 /services endpoint may be queried with optional taxonomy and taxonomy_id parameters
