### ISSUE TITLE
Website link in README 404s

### ISSUE THREAD

**Issue by switzersc** [openreferral/api-specification#81]
This link ( https://openreferral.github.io/api-specification/definition/) on line 5 of the README goes to a page that is not found, and when I remove `definition` from the URL, I see an API evangelist style page for a split second before it redirects to the OpenReferral [readthedocs page](https://openreferral.readthedocs.io/en/latest/). Not sure if there's a DNS issue or if this is intentional.

**Comment by kinlane** [comment]
Hi shelby, thank for reporting. I updated the link to go to the new version of the documentation over at Read the Docs. Found a couple other places it didn't work either....much appreciated.
