### ISSUE TITLE
HSDA Search Sprint

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#84]
I started focusing on HSDA search features during the latest push of the specification. This work spans multiple HSDA services, but focuses on expanding and standardizing the search interface for HSDA--setting the stage for discussions this week.

If you follow the GitHub repository you might have received a barrage of notifications, but this should help focus on the features available for this sprint:

- **Secure Search HSDA** - Adding a secure search to HSDA, allowing POST searches using definition schema as BODY.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427612848
  - OpenAPI: https://gist.github.com/kinlane/e27557e87a5007b6e0014d9437b2bcc9
  - Issue: https://github.com/openreferral/api-specification/issues/86

- **Service Locations** - Adding the other side of service_at_locations, allowing for pulling of services by locations, and locations by services.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427616373
  - OpenAPI: https://gist.github.com/kinlane/5ba7df7901473fd39e89f1183328eddd
  - Issue: https://github.com/openreferral/api-specification/issues/87

- **Add Contacts & Programs** - Adding contacts and programs to the HSDA search results, expanding beyond just organization, locations, and services.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619836
  - OpenAPI: https://gist.github.com/kinlane/00765ecefb966e4fec799b4d66483f48
  - Issue: https://github.com/openreferral/api-specification/issues/88

- **HSDA Proximity Search Parameters (latitude, longitude, radius)** - Adding proximity search for HSDA, across all the core resources (organization, locations, and services).
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427617474
  - OpenAPI: https://gist.github.com/kinlane/d412b5adbd69fae2b5f6a761e1bfdef3
  - Issue: https://github.com/openreferral/api-specification/issues/89

- **HSDA Search Proximity Search Parameters (latitude, longitude, radius)** - Adding proximity search for HSDA Search, across all the core resources (organization, locations, and services).  
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427617594 
  - OpenAPI: https://gist.github.com/kinlane/292f5a1701397c7843ce424edd4107cd
  - Issue: https://github.com/openreferral/api-specification/issues/90

- **HSDA Postal Code Search Parameters** - Adding postal code search for HSDA, allowing searching using proximity across all core resources.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619061 
  - OpenAPI: https://gist.github.com/kinlane/d29bcb807f9a4cf8c66487430845b754
  - Issue: https://github.com/openreferral/api-specification/issues/91

- **HSDA Search Postal Code Search Parameters** - Adding postal code search for HSDA search, allowing searching using proximity across all core resources. 
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619145
  - OpenAPI: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619145
  - Issue: https://github.com/openreferral/api-specification/issues/92

- **HSDA Taxonomies** - Adding the ability to manage taxonomies, so we can search against them.
  - Origin: https://github.com/openreferral/api-specification/issues/73#issuecomment-427621557
  - OpenAPI: https://gist.github.com/kinlane/dcac462b4c6b7c058b23d381cf3e6f23
  - Issue: https://github.com/openreferral/api-specification/issues/93

- **HSDA Taxonomies Search** - Adding the ability to search for taxonomies across core resources (organization, locations, and services) in HSDA.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427622131
  - OpenAPI: https://gist.github.com/kinlane/ba0de5614f3d2433cf77f0604b77e85a
  - Issue: https://github.com/openreferral/api-specification/issues/94

- **HSDA Search Taxonomies** - Adding the ability to search for taxonomies across core resources (organization, locations, and services) in HSDA Search.
  - Origin: https://github.com/openreferral/api-specification/issues/46#issuecomment-427622362 
  - OpenAPI: https://gist.github.com/kinlane/2042c0b2e6a50cddf0039d4bb144cb50
  - Issue: https://github.com/openreferral/api-specification/issues/95

- **HSDA Count Headers** - Adding page count headers for each of the core resources (organization, locations, and services).
  - Origin: https://github.com/openreferral/api-specification/issues/82#issue-367517429 
  - OpenAPI: https://gist.github.com/kinlane/9480759338b86c1420613fbc437a81c2
  - Issue: https://github.com/openreferral/api-specification/issues/96

This is an attempt to satisfy 75% of the requests made across the [HSDA search discussions that are tagged hsda-search](https://github.com/openreferral/api-specification/issues?q=is%3Aissue+is%3Aopen+label%3Ahsda-search).

Then set the stage for discussion during the next HSDA discussion focused on search.

**Comment by kinlane** [comment]
Ok, I added a separate issue for every new feature across HSDA and HSDA Search above. Allowing for their own comment threads.

Next, I will be adding an updated OpenAPI from each of those for HSDA and HSDA Search.

**Comment by NeilMcKechnie** [comment]
Thanks Kin both for the summary here as well as splitting all of them out to separate threads.

**Comment by NeilMcKechnie** [comment]
Hi @kinlane do you have a timeline for when you'll start solidifying these ideas and creating the next draft Search API spec ? It's been great to fragment the ideas out and discuss them separately, but I think they need to coalesce in the near future back to a proposed spec so we can do another round of feedback. Thanks!

**Comment by greggish** [comment]
@NeilMcKechnie thx for working with us through this process.

I wonder if we might be able to get more feedback at this point to inform Kin's next session. For example, my understanding is that Kin put forth several sets of redundant issues (proximity, postal code, and taxonomy code search) to solicit feedback about whether these features should indeed be included in the 'core' spec, as well as the 'advanced' Search spec. Do you have thoughts on this?

Also, I've wondered for a while whether Contacts should be a core HSDA resource (as it currently is) or whether that might be unnecessary complexity. If I understand correctly, #88 now suggests to add Contacts to Search... in which case perhaps it could be removed from the core. Kin and I discussed the matter of use cases for Contacts in core [around 35:25 in this chat](https://www.youtube.com/watch?v=6lSFt3CYbAk) (notes [here](https://docs.google.com/document/d/1935WRo1M4QJd6wSZ_qCJtFIYkOWm31yxEV1O6D5kvL4/edit#heading=h.uz4k7m825iz4)), and i suspect it's an issue we might be able to refine with feedback from stakeholders.

(@kinlane please check my reasoning here!)

**Comment by kinlane** [comment]
I have gone through feedback for all features on this sprint. The only two evolutionary comments I've found are:

- Not using secure_search for new endpoint, and just using POST on existing endpoint #86 
- Using boolean option for search service by taxonomy #76 

Next steps will be to compile complete OpenAPI for each service, and submit proposed version change.

Then I will be looking beyond this sprint to other issues and potential features.

**Comment by kinlane** [comment]
I am adopting an approach similar to GitHubs:

- [Github](https://docs.github.com/en/free-pro-team@latest/rest/reference/search)
- [Working thoughts](https://github.com/openreferral/api-specification/blob/master/query.md)
