### ISSUE TITLE
HSDA Postal Code Search Parameters

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#91]
Adding postal code search for HSDA, allowing searching using proximity across all core resources.

  - Issue: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619061 
  - OpenAPI: https://gist.github.com/kinlane/d29bcb807f9a4cf8c66487430845b754

**Comment by NeilMcKechnie** [comment]
Just want to point out for this to work properly, the entity hosting the data needs a reliable lat/long approximation for each postal code to get reasonably accurate results. Unfortunately, postal codes can be geographically quite large (see rural Canada for example, hundreds of square kilometers each). It's better than nothing, but far from perfect. Caveat emptor.

**Comment by kinlane** [comment]
OpenReferral can only speak to the schema, and access via the API to the schema. I would say that quality / scope of functionality behind interface is out of scope of this work.

**Comment by MikeThacker1** [comment]
In the UK we have asked implementation to support a syntax like this /services?postcode=BS3%204AQ&proximity=5000 with proximity in metres.

**Comment by kinlane** [comment]
I am proposing we adopt an approach similar to GitHubs:

- [Github](https://docs.github.com/en/free-pro-team@latest/rest/reference/search)
- [Working thoughts](https://github.com/openreferral/api-specification/blob/master/query.md)
