### ISSUE TITLE
HSDA Search Postal Code Search Parameters

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#92]
Adding postal code search for HSDA search, allowing searching using proximity across all core resources. 

  - Issue: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619145
  - OpenAPI: https://github.com/openreferral/api-specification/issues/46#issuecomment-427619145

**Comment by boxfoot** [comment]
What's the difference between this and #91 ?

**Comment by NeilMcKechnie** [comment]
Looks like a duplicate to me too.

**Comment by kinlane** [comment]
Not a duplicate. Both HSDA and HSDA Search allow for search by postal code. Just keeping each system with their own example, and conversation.

**Comment by kinlane** [comment]
I am proposing we adopt an approach similar to GitHubs:

- [Github](https://docs.github.com/en/free-pro-team@latest/rest/reference/search)
- [Working thoughts](https://github.com/openreferral/api-specification/blob/master/query.md)
