### ISSUE TITLE
HSDA Taxonomies

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#93]
Adding the ability to manage taxonomies, so we can search against them.

  - Issue: https://github.com/openreferral/api-specification/issues/73#issuecomment-427621557
  - OpenAPI: https://gist.github.com/kinlane/dcac462b4c6b7c058b23d381cf3e6f23

**Comment by NeilMcKechnie** [comment]
@kinlane , can you define "manage" more clearly here, as well as why managing taxonomies is important for them to be searchable, to elicit comments?

**Comment by kinlane** [comment]
This is not about searching taxonomies. This is about adding, updating, getting, and removing taxonomies all by themselves.  Aside from applying them to any service, or searching using them. Essentially you cannot apply or search for what does not exist.

**Comment by greggish** [comment]
@kinlane can you clarify if this really means adding / updating / getting multiple taxonomies (as in multiple categorical schema) or do you mean managing a taxonomy by adding / updating / getting / removing taxonomic codes?

This is one of the hardest parts of our problem, which we haven't really tackled yet from a design perspective...

**Comment by kinlane** [comment]
I can confirm my intent with new functionality is to allow the:

adding / updating / getting multiple taxonomies (as in multiple categorical schema)

as well as:

adding / updating / getting / removing taxonomic codes

It should do both.

**Comment by kinlane** [comment]
The new schema has been implemented. We can rely on new comments on V2.0.
