### ISSUE TITLE
Upgrade to OpenAPI v3

### ISSUE THREAD

**Issue by greggish** [openreferral/api-specification#97]
I'm told we're using OpenAPI spec v.2 and that we should upgrade at some point soon to v.3

**Comment by kinlane** [comment]
Yep. The next iteration will be in 3.0. #goodreminder

**Comment by kinlane** [comment]
I have converted [HSDA v1.2 to OpenAPI 3.0 and published to a public workspace](https://www.postman.com/api-evangelist/workspace/open-referral-human-services-data-api-hsda/api/1a7abc09-be01-45fa-932c-7ed3d11e43ea?version=f46b5eea-ae95-4849-a8a5-24bbfcc95a75&tab=define). I have also copied it and established a [https://www.postman.com/api-evangelist/workspace/open-referral-human-services-data-api-hsda/api/1a7abc09-be01-45fa-932c-7ed3d11e43ea?version=2c338c6f-4da0-452c-bb5d-ef834c1ce7cc&tab=define](v2.l0 base in OpenAPI 3.0) as well.
